server:
  port: 12002
rabbitmq:
  queue: "my.queue"
dynamodb:
  tableName: "my-db"
aws:
  region: "eu-central-1"
  accessKeyId: "foo"
  secretAccessKey: "bar"
  endpoint: "http://localstack:4566"
spring:
  rabbitmq:
    addresses: "rabbitmq:5672"
    username: "downstream-user"
    password: "password"
logging:
  level:
    root: info
    com.example: debug
management:
  tracing:
    propagation:
      type: b3
